name: BoosterPlugin
version: ${project.version}
main: io.github.jordieh.boosters.BoosterPlugin
depend: [Vault]

commands:
  booster:
    usage: /<command> <player> <percentage> <duration> [amount]
  boosters:
    usage: /<command>
